apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: backend
spec:
  # type: LoadBalancer
  # type: NodePort
  # type: ExternalName
  type: ClusterIP
  # externalName: express.api.com
  # clusterIP: 10.43.0.1
  selector:
    app: express-api
  ports:
    - port: 80
      targetPort: 3000
      # nodePort: 32177
