apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: kube-full-stack-express-api:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: rootpassword
            - name: DB_NAME
              value: testdb
            - name: PG_DB_HOST
              value: "pgsql-service"
            - name: PG_DB_USER
              value: mypguser
            - name: PG_DB_PASSWORD
              value: mypgpassword
            - name: PG_DB_NAME
              value: mypgdatabase
          ports:
            - containerPort: 3000
