apiVersion: v1
kind: Service
metadata:
  name: pgsql-service
spec:
  type: LoadBalancer
  selector:
    app: pgsql-deployment
  ports:
    - port: 5432
      targetPort: 5432 # Matches the containerPort in deployment
  selector:
    app: pgsql
