apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: pgsql-app-db
          image: postgres:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_USER
              value: mypguser
            - name: POSTGRES_PASSWORD
              value: mypgpassword
            - name: POSTGRES_DB
              value: mypgdatabase
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgsql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgsql-data
          persistentVolumeClaim:
            claimName: pgsql-pvc
