apiVersion: v1
kind: Service
metadata:
  name: pgsql-db
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: pgsql-sts
  ports:
    - port: 5432
      targetPort: 5432 # Matches the containerPort in deployment/statefulset
  selector:
    app: pgsql